# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
