# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logreg_app', '0003_remove_user_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsWritten', to='logreg_app.User')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='logreg_app.User')),
            ],
        ),
    ]
